// export const CURRENT_SCROLL_TOP = 'CURRENT_SCROLL_TOP';
// export const IS_LOADING = 'IS_LOADING'
// // export const ACCOUNT_DATA = 'ACCOUNT_DATA';

export const SHOW_PRODUCT_ALL_SPEC_MODAL = 'SHOW_PRODUCT_ALL_SPEC_MODAL';

